project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Econ115a lab"
  favicon: "plot/econ115a-hex-logo.png"
  
  repo-url: https://github.com/Econ-115a-Econometrics/econ115a-lab-site
  site-url: https://econ-115a-econometrics.github.io/econ115a-lab-site/
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/econ115a-hex-logo.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "m1-intro-r.qmd"
            text: "Module 1: Introduction to R programming"
          - href: "m2-intro-data-viz-ggplot.qmd"
            text: "Module 2: Intro to data visualization using ggplot2"
          - href: "m3-reproducible-quarto.qmd"
            text: "Module 3: Reproducible report with Quarto in R"
          - href: "m5-exploratory-data-analysis.qmd"
            text: "Module 5: exploratory data analysis"
          - href: ""
            text: "Module 6: exploring assumptions"
          - href: ""
            text: "Module 7: correlation and regression analysis"
          - href: ""
            text: "Module 8: limited-dependent variable models"
          - href: ""
            text: "Module 9: non-parametric tests"
          - href: ""
            text: "Module 10: Exploratory factor analysis (EFA)"  
      - section: "Assignment"
        contents:
          - href: "01-assignment1-coffee-sales.qmd"
            text: "Module 1 assignment"
      - section: "Midterm and Finals projects"
        contents:
          - href: "term-01-midterm-project.qmd"
            text: "Midterm project: Shopping behavior analysis"

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual

